GET http://localhost:8888/hello

###

POST http://localhost:8888/hello
Content-Type: application/json

{"name": "chenchen"}

###

GET http://localhost:9999/a/hello

###

POST http://localhost:9999/hello
Content-Type: application/json

{"name": "chenchen"}

###
